format = """
[](bright-purple)\
$username\
[](bg:bright-blue fg:bright-purple)\
$directory\
[](fg:bright-blue bg:bright-yellow)\
$git_branch\
$git_status\
[](fg:bright-yellow bg:bright-cyan)\
$c\
$golang\
$nodejs\
$python\
$rust\
[](fg:bright-cyan bg:bright-green)\
$docker_context\
[](fg:bright-green bg:bright-black)\
$time\
[ ](fg:bright-black)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:bright-purple fg:black"
style_root = "bg:bright-purple fg:black"
format = '[$user ]($style)'

[directory]
style = "bg:bright-blue fg:black"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[c]
symbol = " "
style = "bg:bright-cyan fg:black"
format = '[[ $symbol ($version) ](bg:bright-cyan fg:black)]($style)'

[docker_context]
symbol = " "
style = "bg:bright-green fg:black"
format = '[[ $symbol $context ](bg:bright-green fg:black)]($style) $path'

[elixir]
symbol = " "
style = "bg:bright-cyan fg:black"
format = '[[ $symbol ($version) ](bg:bright-cyan fg:black)]($style)'

[elm]
symbol = " "
style = "bg:bright-cyan fg:black"
format = '[[ $symbol ($version) ](bg:bright-cyan fg:black)]($style)'

[git_branch]
symbol = ""
style = "bg:bright-yellow fg:black"
truncation_length = 32
format = '[[ $symbol $branch ](bg:bright-yellow fg:black)]($style)'

[git_status]
style = "bg:bright-yellow fg:black"
format = '[[($all_status$ahead_behind )](bg:bright-yellow fg:black)]($style)'

[golang]
symbol = " "
style = "bg:bright-cyan fg:black"
format = '[[ $symbol ($version) ](bg:bright-cyan fg:black)]($style)'

[haskell]
symbol = " "
style = "bg:bright-cyan fg:black"
format = '[[ $symbol ($version) ](bg:bright-cyan fg:black)]($style)'

[java]
symbol = " "
style = "bg:bright-cyan fg:black"
format = '[[ $symbol ($version) ](bg:bright-cyan fg:black)]($style)'

[julia]
symbol = " "
style = "bg:bright-cyan fg:black"
format = '[[ $symbol ($version) ](bg:bright-cyan fg:black)]($style)'

[nodejs]
symbol = ""
style = "bg:bright-cyan fg:black"
format = '[[ $symbol ($version) ](bg:bright-cyan fg:black)]($style)'

[nim]
symbol = " "
style = "bg:bright-cyan fg:black"
format = '[[ $symbol ($version) ](bg:bright-cyan fg:black)]($style)'

[python]
symbol = " "
style = "bg:bright-cyan fg:black"
format = '[[ $symbol ($version) ](bg:bright-cyan fg:black)]($style)'

[conda]
symbol = "🅒 "
style = "bg:bright-cyan fg:black"
format = '[[ $symbol ($version) ](bg:bright-cyan fg:black)]($style)'

[rust]
symbol = ""
style = "bg:bright-cyan fg:black"
format = '[[ $symbol ($version) ](bg:bright-cyan fg:black)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:bright-black fg:white"
format = '[[ ♥ $time ](bg:bright-black fg:white)]($style)'
